### PR TITLE
feat: Gitlab provider

### PR DESCRIPTION
**Pull request by omri2001**
Add support for GitLab as a provider

### CODE REVIEW

**Comment by GoshaDo** [comment]
@ssliman moved to this PR

**Comment by ssliman** [comment]
Thanks! looking forward to test this out. Will it be merged this week?

**Comment by GoshaDo** [comment]
> Thanks! looking forward to test this out. Will it be merged this week?

merged.
will be great to get your feedback :)

**Comment by ssliman** [comment]
@GoshaDo I've set it up with our selfhosted gitlab and it works. Thank you for providing this support.

One missing feature that could be implemented is that we have multiple gitlab projects and currently with the current piper version we only provide 1 project through the `values.yaml`

```
  piper:
    gitProvider:
      name: gitlab
      # Map of organization configurations.
      organization:
        # -- Name of your Git Organization (GitHub) / Workspace (Bitbucket) or Group (Gitlab)
        name: "private/k8s"
      # Map of webhook configurations.
      webhook:
        # -- (Github/Gitlab) Used of orgLevel=false, to configure webhook for each of the repos provided.
        repoList: ["some-repo"]
```

if we want repositories from other groups/projects that's not possible.

**Comment by GoshaDo** [comment]
> @GoshaDo I've set it up with our selfhosted gitlab and it works. Thank you for providing this support.
> 
> One missing feature that could be implemented is that we have multiple gitlab projects and currently with the current piper version we only provide 1 project through the `values.yaml`
> 
> ```
>   piper:
>     gitProvider:
>       name: gitlab
>       # Map of organization configurations.
>       organization:
>         # -- Name of your Git Organization (GitHub) / Workspace (Bitbucket) or Group (Gitlab)
>         name: "private/k8s"
>       # Map of webhook configurations.
>       webhook:
>         # -- (Github/Gitlab) Used of orgLevel=false, to configure webhook for each of the repos provided.
>         repoList: ["some-repo"]
> ```
> 
> if we want repositories from other groups/projects that's not possible.

@omri2001 Interesting feature.. 
@ssliman Can you please open an issue with the description (That you just provided) so you can be updated automatically for the progress of this issue ?

**Comment by GoshaDo** [comment]
@ssliman btw, if you will configure the webhook in project level, it should work..
The secret for authentication can be found in K8s secret, where piper installed.. 
Screenshot 2025-01-06 at 13 39 51

**Comment by ssliman** [comment]
@GoshaDo thanks indeed. Yes it does work, but if you have like a lot of repositories across different groups that's a lot of manual work. I could create a script that does it for me. It would be nice if it's handled by piper automatically.

**Comment by ssliman** [comment]
Feature request created under #30

**Pull request merged**
